### ISSUE TITLE
Request for Assistance with Data Access for Research Paper Data

### ISSUE THREAD

**Issue by Aaronself** [joaqgonzar/Gamma_Oscillations_PCx#2]
I'm a scholar deeply interested in Dr. Joaquin Gonzalez's research paper "Mechanisms and Functions of Respiration-driven Gamma Oscillations in the Primary Olfactory Cortex." However, I've encountered problems accessing the associated data on the provided website, which seems to be down. Meanwhile, this data appears to be incomplete compared to the original paper "Recurrent cortical circuits implement concentration-invariant odor coding."

Could Dr. Gonzalez kindly assist in resolving this issue or provide an alternative data access method? Access to the complete dataset is critical for my research.

Thank you!

**Comment by joaqgonzar** [comment]
Hi,

I reuploaded the recordings to Figshare. Can you try to download the recordings from the following link ? 
https://figshare.com/articles/dataset/Decimated_LFPs_Gonzalez_2023/24139059

Regarding the discrepancy between the data I uploaded and the original publication, I note that only the data employed in my paper was the one uploaded. There are some experiments (reported in the original publication) available at CRCNS (https://crcns.org/data-sets/pcx/pcx-1) that I did not employ, and did not preprocess.  

Hope you are now able to download the recordings, otherwise, let me know.

**Comment by Aaronself** [comment]
Hi,

Thanks a lot! I can download the file from the new link!
